from snakemake.io import glob_wildcards,strip_wildcard_constraints,get_wildcard_names
import snakebids
from snakebids import bids

configfile: 'config.yml'

# Get input wildcards
inputs = snakebids.generate_inputs(
    bids_dir=config["bids_dir"],
    pybids_inputs=config["pybids_inputs"],
    pybids_database_dir=config.get("pybids_db_dir"),
    pybids_reset_database=config.get("pybids_db_reset"),
    derivatives=config.get("derivatives", None),
    participant_label=config.get("participant_label", None),
    exclude_participant_label=config.get("exclude_participant_label", None),
)

subjects = inputs.subjects
subj_wildcards=inputs.subj_wildcards

#this adds constraints to the bids naming
wildcard_constraints:  **snakebids.get_wildcard_constraints(config['pybids_inputs'])

#---- end snakebids boilerplate ------------------------------------------------


rule all:
    input:
        expand('hippunfold_{variant}_{version}/hippunfold/sub-{subject}',subject=inputs.subjects,variant=config['variant_opts']['hippunfold'].keys(),version=config['singularity']['hippunfold'].keys()),
        expand('snakedwi/sub-{subject}',subject=inputs.subjects)

include: 'rules/hippunfold.smk'
include: 'rules/snakedwi.smk'




