
bids_dir: /scratch/akhanf/2_datasets/eplink_mri/eplink-spred2bids-noheudi/bids_baseline


singularity:
  fmriprep: '/project/6050199/akhanf/singularity/bids-apps/nipreps_fmriprep_23.1.0.sif'
  hippunfold: '/project/6050199/akhanf/singularity/bids-apps/khanlab_hippunfold_v1.0.0.sif'
  freesurfer: '/project/6050199/akhanf/singularity/bids-apps/freesurfer_freesurfer_7.2.0.sif'


fs_license_file: '/project/ctb-akhanf/akhanf/opt/freesurfer/.license'

pybids_inputs:
  dwi:
    filters:
      suffix: 'dwi'
      extension: '.nii.gz'
      datatype: 'dwi'
    wildcards:
      - subject
      - session
      - acquisition
      - run
      - direction
  t1:
    filters:
      suffix: 'T1w'
      extension: '.nii.gz'
      datatype: 'anat'
    wildcards:
      - subject
      - session
      - acquisition
      - run




