
bids_dir: /project/6050199/akhanf/cfmm-bids/data/Kohler/HcECT/bids

opts:
  hippunfold: '--keep-work --atlas bigbrain'
  snakedwi: '--use-eddy-gpu --use-singularity --singularity-prefix $SNAKEMAKE_SINGULARITY_DIR'

variant_opts:
  hippunfold:
    t1: '--modality T1w'
    t1_synthseg: '--modality T1w --force-nnunet-model synthseg_v0.2'
    t2: '--modality T2w --output-spaces T1w --t1-reg-template --generate-myelin-map'
    t2_synthseg: '--modality T2w --output-spaces T1w --t1-reg-template --generate-myelin-map --force-nnunet-model synthseg_v0.2'
  hippunfolddwi:
    b500: '--modality hippb500'
    b500_synthseg: '--modality hippb500 --force-nnunet-model synthseg_v0.2'

singularity:
  hippunfold:
    v1.3.3: '/project/6050199/akhanf/singularity/bids-apps/khanlab_hippunfold_v1.3.3.sif'


fs_license_file: '/project/ctb-akhanf/akhanf/opt/freesurfer/.license'

pybids_inputs:
  dwi:
    filters:
      suffix: 'dwi'
      extension: '.nii.gz'
      datatype: 'dwi'
    wildcards:
      - subject
      - session
      - acquisition
      - run
      - direction
  t1:
    filters:
      suffix: 'T1w'
      extension: '.nii.gz'
      datatype: 'anat'
    wildcards:
      - subject
      - session
      - acquisition
      - run


pybids_inputs_dwionly:
  dwi:
    filters:
      suffix: 'dwi'
      extension: '.nii.gz'
      datatype: 'dwi'
    wildcards:
      - subject
      - session
      - acquisition
      - run
      - direction



